### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by undavide** [chrisenytc/slush-generator#12]
Hi,
just installed gulp, slush, and slush-generator on a brand new machine (OSX 10.10.5), created a new folder and:

```
slush generator
/usr/local/lib/node_modules/slush-generator/slushfile.js:50
    authorName: user.name || '',
                    ^
TypeError: Cannot read property 'name' of undefined
    at /usr/local/lib/node_modules/slush-generator/slushfile.js:50:25
    at Object.<anonymous> (/usr/local/lib/node_modules/slush-generator/slushfile.js:53:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/slush/bin/slush.js:90:3)
    at Liftoff.launch (/usr/local/lib/node_modules/slush/node_modules/liftoff/index.js:153:6)
```

Any help is appreciated!
Thank you,

-Davide

**Comment by chrisenytc** [comment]
I will fix this soon as possible. :+1:

**Comment by closingin** [comment]
@chrisenytc I think you can close this issue. It's been a while since I fixed it.

**Comment by chrisenytc** [comment]
Indeed @closingin
